dataset:
  name: cifar10
  data_root: ../data
  num_workers: 2

train:
  batch_size: 128
  epochs: 10
  seed: 42
  w1: 0.3
  w2: 0.3
  w3: 1.0

optimizer:
  lr: 0.01
  momentum: 0.9
  weight_decay: 5e-4

model:
  name: resnet18
